[phases.setup]
nixPkgs = ['dotnet-sdk_8']

[phases.install]
cmd = "dotnet restore ./FullStackCrud.Server/FullStackCrud.Server.csproj"

[phases.build]
cmd = "dotnet publish ./FullStackCrud.Server/FullStackCrud.Server.csproj -c Release -o out"

[phases.start]
cmd = "./out/FullStackCrud.Server"
