services:
  - type: web
    name: dotnet8-api
    repo: https://github.com/your-username/your-repo
    branch: main
    plan: free
    dockerContext: ./FullStackCrud.Server
    dockerfilePath: ./FullStackCrud.Server/Dockerfile


